### ISSUE TITLE
Question: Have Any Positive Searches Been Made?

### ISSUE THREAD

**Issue by Mike-EEE** [SjorsO/keys#28]
Hello,

First off, very inspiring and impressive project here.  Thank you for taking the time to build it and make it available.

I recently found out about this in a Telegram group, where someone made the claim they found an address after an hour of using this service, with a dust amount of ETH (0.0000001).

That led me to investigate this whole area further, as I have a Ledger Nano S and wanted to make sure that I understood that if someone found my key using your application, that they could simply move funds without having the need for the Ledger altogether.

So I posted this question on Reddit, referencing your site here FWIW:
https://www.reddit.com/r/ledgerwallet/comments/b89lhu/ledger_wallet_private_keys_for_btceth_available/

Reddit being reddit, of course, you can read and see that rather than confirming that this is a legitimate security issue with the Ledger devices, I got downvoted and into a discussion about the odds of actually finding a value-positive key. 😆😂😁

As you can further see by the discussion, the legitimacy of someone actually finding a value-positive key is being called into question.  That led me to the thought of asking here if there are any records that you keep that show when a positive hit is made when an account has more than 0 value.

And, if not, if this is something that you would consider implementing.

Thank you in advance for any consideration and/or assistance!

**Comment by SjorsO** [comment]
All the balance checking happens on the client side, so i can't know if anyone actually finds anything. However, statistically speaking, the chance that someone has actually found something after pressing the "random page" button is zero.

I won't be implementing a feature that keeps track of if people find an active wallet. Both because it would mean moving the balance checking from the client side to the server side, and it would make the site less trustworthy (people already have trouble trusting this site, even though it is open source). Also, since nobody will ever actually find anything, implementing such a feature would be a waste of time 😄 

I'm closing this issue, but if you have any more questions, feel free to add them as a comment.

**Comment by Mike-EEE** [comment]
Ah!  Ok thank you for your reply.

To be sure, the ask isn't to keep track of the wallet id itself, but that a positive find has been made.

FWIW, there is someone who is already claiming to have made a positive find using your site:
https://www.reddit.com/r/ledgerwallet/comments/b89lhu/ledger_wallet_private_keys_for_btceth_available/ejyh8i9/
