### ISSUE TITLE
dont know what must i do....

### ISSUE THREAD

**Issue by k356** [SjorsO/keys#61]
In PackageManifest.php line 131:

  Undefined index: name

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

when i run composer install and next step

**Comment by carbohydration** [comment]
No, Don't bother trying to build this. Don't even bother using this website. All the values are hard coded. You will never find any balances because there are no balances to find.

Take a look at this private key: 5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEsreAvUcVfH

You see there is a lot of activity, yet the website displays it as (? tx). This website is completely fake and only made to get penny ad money. Very shameful, don't support this person.

**Comment by k356** [comment]
i find solution....
run composer update,and then repeat step from composer install ...
and finally work
